### ISSUE TITLE
Support for https://m.youtube.com/* links

### ISSUE THREAD

**Issue by SilencerWeb** [Spmart/YTAP-Bot#1]

**Comment by Spmart** [comment]
https://m.youtube.com/* links now supported!
![Снимок экрана 2020-08-09 в 22 33 49](https://user-images.githubusercontent.com/12640673/89740336-67369e80-da90-11ea-8690-10b2809500e1.png)

**Comment by SilencerWeb** [comment]
Thanks a lot!
