### ISSUE TITLE
An ability to give feedback

### ISSUE THREAD

**Issue by SilencerWeb** [Spmart/YTAP-Bot#2]
Would be awesome to have an ability to give feedback through the bot, or just a username of the creator or link to this repo in bot's description :)

**Comment by Spmart** [comment]
Done!
![Снимок экрана 2020-07-21 в 11 55 44](https://user-images.githubusercontent.com/12640673/88034344-3c1ff580-cb49-11ea-9cb7-25314d7c780f.png)
