### ISSUE TITLE
Support for longer videos

### ISSUE THREAD

**Issue by SilencerWeb** [Spmart/YTAP-Bot#4]
Also, would be awesome if the bot would tell what's video length limit, seems like it is about 45-50 minutes

**Comment by Spmart** [comment]
The bot says about the limit if the video is too long (>50 min). Soon I will release a feature that will allow downloading long audio. I think, 3 or 4 hours is enough.

**Comment by Spmart** [comment]
Done in 7eac60e. Now we can download really long files — up to 5 hours.
![Снимок экрана 2020-08-09 в 22 30 43](https://user-images.githubusercontent.com/12640673/89740281-f8594580-da8f-11ea-8a4c-fb90e08f63f9.png)

**Comment by SilencerWeb** [comment]
Woohoo!
